### ISSUE TITLE
Parse Failed when run hugo server

### ISSUE THREAD

**Issue by ZekeriyaAY** [apvarun/showfolio-hugo-theme#5]
`Error: add site dependencies: load resources: loading templates: "/mnt/c/Users/z3k/Desktop/zekeriyaay/themes/showfolio/layouts/partials/codepen-gallery.html:2:1": parse failed: template: partials/codepen-gallery.html:2: range can only initialize variables`

**Comment by apvarun** [comment]
Looks like template formatting issue. I've updated some template [code](https://github.com/apvarun/showfolio-hugo-theme/commit/d697f8ed23492584f4d3f742d27db9d1f5c38644)

Can you pull the latest changes and check it? 

If you still have issue, please share the hugo version and your OS.

**Comment by ZekeriyaAY** [comment]
I cloned the latest theme again.

New error: 
`Error: add site dependencies: load resources: loading templates: "/mnt/c/Users/z3k/Desktop/websites/showfolio/themes/showfolio/layouts/partials/head.html:10:1": parse failed: template: partials/head.html:10: unclosed action`

Hugo Vers: Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
OS: Ubuntu on WSL2

**Comment by tylerkennedy** [comment]
I got the same error after cloning the latest version. This was my quick fix in `showfolio/layouts/partials/head.html:10`

`{{- if .Keywords }} <meta name="keywords" content="{{ delimit.Keywords ',' }}" />`

**Comment by ZekeriyaAY** [comment]
> I got the same error after cloning the latest version. This was my quick fix in `showfolio/layouts/partials/head.html:10`
> 
> `{{- if .Keywords }} <meta name="keywords" content="{{ delimit.Keywords ',' }}" />`

Solved the problem but gave new error.
`Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): resource "css/css/styles.css_2470d520f8390e01a1a99d32c19f09b5" not found in file cache`

**Comment by apvarun** [comment]
The minimum version of hugo required for the theme is [0.69.0](https://github.com/apvarun/showfolio-hugo-theme/blob/main/theme.toml#L11)

The theme requires PostProcess which was only added in version 0.69

**Comment by ZekeriyaAY** [comment]
Thank you for the information. 
This requirement can be added to the readme.
