### ISSUE TITLE
Where are the social icons from? I'd like to add a few

### ISSUE THREAD

**Issue by cosmotek** [apvarun/showfolio-hugo-theme#7]
I'd like to add an icon for my phone, as well as email and a file icon for PDFs. I love the existing social icons, and was hoping you'd be willing to share info as to where they came from. I assume there will be other icons in the same style available there.

**Comment by apvarun** [comment]
Hi @cosmotek, all the icons are from https://tablericons.com/

Feel free to submit PR's by adding more social icons :)
